version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 19000:9000
      - 8001:8001
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse/
      - ./enable_prometheuse.conf:/etc/clickhouse-server/config.d/config.xml

